---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    name: carts
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.carts.replicaCount }}
  selector:
    matchLabels:
      name: carts
  template:
    metadata:
      labels:
        name: carts
    spec:
      containers:
        - name: carts
          image: {{ .Values.carts.image.name }}:{{ .Values.carts.image.tag }}
          env:
            - name: {{ .Values.java.options.name }}
              value: {{ .Values.java.options.value }}
          resources:
{{ toYaml .Values.carts.resources | indent 10 }}
          ports:
            - containerPort: {{ .Values.carts.containerPort }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.carts.containerPort }}
            initialDelaySeconds: 420
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.carts.containerPort }}
            initialDelaySeconds: 360
            periodSeconds: 3
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
{{/*      nodeSelector:*/}}
{{/*        beta.kubernetes.io/os: linux*/}}