---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.catalogue.replicaCount }}
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
    spec:
      containers:
        - name: catalogue
          image: {{ .Values.catalogue.image.name }}:{{ .Values.catalogue.image.tag }}
          command: [ "/app" ]
          args:
            - -port=80
          resources:
{{ toYaml .Values.catalogue.resources | indent 10 }}
          ports:
            - containerPort: {{ .Values.catalogue.containerPort }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.catalogue.containerPort }}
            initialDelaySeconds: 300
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.catalogue.containerPort }}
            initialDelaySeconds: 180
            periodSeconds: 3
{{/*      nodeSelector:*/}}
{{/*        beta.kubernetes.io/os: linux*/}}