---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: catalogue
  namespace: {{ .Values.namespace }}
spec:
  ports:
    # the port that this service should serve on
    - port: {{ .Values.catalogue.containerPort }}
      targetPort: {{ .Values.catalogue.containerPort }}
  selector:
    name: catalogue