---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: front-end
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.service.ports.port }}
      targetPort: {{ .Values.frontend.service.ports.targetPort }}
      nodePort: {{ .Values.frontend.service.ports.nodePort }}
  selector:
    name: front-end