---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
        - name: front-end
          image: {{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
          resources:
{{ toYaml .Values.frontend.resources | indent 10 }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: SESSION_REDIS
              value: "{{ .Values.frontend.env.SESSION_REDIS }}"
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: 300
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 3
{{/*      nodeSelector:*/}}
{{/*        beta.kubernetes.io/os: linux*/}}
