---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    name: orders
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.orders.replicaCount }}
  selector:
    matchLabels:
      name: orders
  template:
    metadata:
      labels:
        name: orders
    spec:
      containers:
        - name: orders
          image: {{ .Values.orders.image.name }}:{{ .Values.orders.image.tag }}
          env:
            - name: {{ .Values.java.options.name }}
              value: {{ .Values.java.options.value }}
          resources:
{{ toYaml .Values.carts.resources | indent 10 }}
          ports:
            - containerPort: {{ .Values.orders.containerPort }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
{{/*      nodeSelector:*/}}
{{/*        beta.kubernetes.io/os: linux*/}}