---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  labels:
    name: orders-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.orders.replicaCount }}
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
        - name: orders-db
          image: {{ .Values.orders.db.image.name }}:{{ .Values.orders.db.image.tag }}
          ports:
            - name: mongo
              containerPort: {{ .Values.orders.containerPort }}
          securityContext:
            capabilities:
              drop:
                - all
              add:
                - CHOWN
                - SETGID
                - SETUID
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
{{/*      nodeSelector:*/}}
{{/*        beta.kubernetes.io/os: linux*/}}