---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.payment.replicaCount }}
  selector:
    matchLabels:
      name: payment
  template:
    metadata:
      labels:
        name: payment
    spec:
      containers:
        - name: payment
          image: {{ .Values.payment.image.name }}:{{ .Values.payment.image.tag }}
          resources:
{{ toYaml .Values.carts.resources | indent 10 }}
          ports:
            - containerPort: {{ .Values.payment.containerPort }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.payment.containerPort }}
            initialDelaySeconds: 300
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.payment.containerPort }}
            initialDelaySeconds: 180
            periodSeconds: 3
{{/*      nodeSelector:*/}}
{{/*        beta.kubernetes.io/os: linux*/}}