---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
  labels:
    name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  ports:
    # the port that this service should serve on
    - port: {{ index .Values.rabbitmq.images.rabbitmq.ports 1 "containerPort" }}
      name: rabbitmq
      targetPort: {{ index .Values.rabbitmq.images.rabbitmq.ports 1 "containerPort" }}
    - port: {{ .Values.rabbitmq.images.rabbitmq_exporter.containerPort }}
      name: exporter
      targetPort: exporter
      protocol: TCP
  selector:
    name: rabbitmq