---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-db
  labels:
    name: session-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.session_db.replicaCount }}
  selector:
    matchLabels:
      name: session-db
  template:
    metadata:
      labels:
        name: session-db
    spec:
      containers:
        - name: session-db
          image: {{ .Values.session_db.image.name }}:{{ .Values.session_db.image.tag }}
          ports:
            - name: redis
              containerPort: {{ .Values.session_db.containerPort }}
          securityContext:
            capabilities:
              drop:
                - all
              add:
                - CHOWN
                - SETGID
                - SETUID
            readOnlyRootFilesystem: true
          resources:
{{ toYaml .Values.session_db.resources | indent 10 }}
