---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user
  namespace: {{ .Values.namespace }}
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: {{ .Values.user.containerPort }}
  selector:
    name: user
