---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    name: user-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    # the port that this service should serve on
    - port: {{ .Values.userdb.containerPort }}
      targetPort: {{ .Values.userdb.containerPort }}
  selector:
    name: user-db
