---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    name: user-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.userdb.replicaCount }}
  selector:
    matchLabels:
      name: user-db
  template:
    metadata:
      labels:
        name: user-db
    spec:
      containers:
        - name: user-db
          image: {{ .Values.userdb.image.repo }}:{{ .Values.userdb.image.tag }}
          ports:
            - name: mongo
              containerPort: {{ .Values.userdb.containerPort }}
          resources:
{{ toYaml .Values.userdb.resources | indent 10 }}
          securityContext:
            capabilities:
              drop:
                - all
              add:
                - CHOWN
                - SETGID
                - SETUID
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
